version: '3.8'
services:
  redis:
    container_name: local-comeon-app-redis
    image: redis:7.0.4
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
    networks:
      default:

networks:
  default:
    name: local-comeon-app-backend
    external: true
