spring:
  config:
    additional-location: config/
  profiles:
    group:
      local: "local,root,datasource,jwt,oauth,aws,logging,kafka,admin"
      dev: "dev,root,datasource,jwt,oauth,aws,logging,kafka,admin"
      prod: "prod,root,datasource,jwt,oauth,aws,logging,kafka,admin"
    active: local
  messages:
    basename: errors
